import type { InventoryItem } from './types';

export const inventoryItems: InventoryItem[] = [
  {
    id: '1',
    name: 'Whole Tenderloin',
    category: 'Meat',
    quantity: 5,
    unit: 'pcs',
    parLevel: 4,
    supplier: 'Prime Cuts Co.',
    expirationDate: '2024-10-15',
    status: 'In Stock',
  },
  {
    id: '2',
    name: 'Avocado',
    category: 'Produce',
    quantity: 10,
    unit: 'kg',
    parLevel: 15,
    supplier: 'Green Farms',
    expirationDate: '2024-10-05',
    status: 'Low Stock',
  },
  {
    id: '3',
    name: 'Sourdough Loaf',
    category: 'Bakery',
    quantity: 2,
    unit: 'pcs',
    parLevel: 10,
    supplier: 'Artisan Breads',
    expirationDate: '2024-10-03',
    status: 'Low Stock',
  },
  {
    id: '4',
    name: 'Salmon Fillet',
    category: 'Seafood',
    quantity: 8,
    unit: 'kg',
    parLevel: 5,
    supplier: 'Ocean Fresh',
    expirationDate: '2024-10-04',
    status: 'In Stock',
  },
  {
    id: '5',
    name: 'Truffle Oil',
    category: 'Pantry',
    quantity: 20,
    unit: 'btl',
    parLevel: 12,
    supplier: 'Gourmet Imports',
    expirationDate: '2025-08-01',
    status: 'In Stock',
  },
  {
    id: '6',
    name: 'Heirloom Tomatoes',
    category: 'Produce',
    quantity: 3,
    unit: 'kg',
    parLevel: 5,
    supplier: 'Green Farms',
    expirationDate: '2024-10-06',
    status: 'Low Stock',
  },
  {
    id: '7',
    name: 'Flour, All-Purpose',
    category: 'Pantry',
    quantity: 50,
    unit: 'kg',
    parLevel: 25,
    supplier: 'Bulk Goods Inc.',
    expirationDate: '2025-01-20',
    status: 'In Stock',
  },
  {
    id: '8',
    name: 'Microgreens Mix',
    category: 'Produce',
    quantity: 0,
    unit: 'kg',
    parLevel: 1,
    supplier: 'Green Farms',
    expirationDate: '2024-10-02',
    status: 'Out of Stock',
  },
];

export const lowStockItems = inventoryItems.filter(
  (item) => item.status === 'Low Stock'
);

export const topSellingItems = [
  { name: 'Filet Mignon (8oz)', category: 'Entrees', unitsSold: 42 },
  { name: 'Truffle Fries', category: 'Appetizers', unitsSold: 35 },
  { name: 'Seared Salmon', category: 'Entrees', unitsSold: 28 },
  { name: 'Classic Old Fashioned', category: 'Beverages', unitsSold: 25 },
  { name: 'Avocado Toast', category: 'Brunch', unitsSold: 21 },
];
